### PR TITLE
Big update

### PR DESCRIPTION
**Pull request by kikolio**

### CODE REVIEW

**Comment by joequery** [comment]
Awesome man, thanks for keeping this up to date!

**Comment by sameg14** [comment]
Did this PR get merged already?

**Comment by joequery** [comment]
It looks like the commits of this PR were squashed and committed manually.  See commit 9176e1362ec658

**Comment by sameg14** [comment]
Aah. Ok cool, just wondering! Good job on the syllabus, looks pretty legit!

**Pull request closed without merging**
